Tali Forth is shipped with a built-in assembler that uses the Simpler Assembler
Format (SAN). See the Appendix for an introduction to SAN.

NOTE: The code was originally part of a stand-alone 65c02 assembler in Forth
named tasm65c02. See https://github.com/scotws/tasm65c02 for details. Tasm65c02
is in the public domain.

==== Adding assembler code at the command line

Because Tali Forth is a Subroutine Threaded (STC) Forth, inserting assembler
instructions is easy. In fact, the only real problem is accessing the assembler
wordlist, which is normally not in the search tree because of its length. This,
then, is one way to add assembler code:

----
        assembler-wordlist >order
        here            \ Remember where we are
        1 lda.#         \ LDA #1 in Simpler Assembler Notation (SAN)
        push-a          \ Pseudo-instruction, pushes A on the Forth data stack
        rts             \ End subroutine. Don't use BRK!
        execute         \ Run our code using value from HERE
        .s              \ Will show 1 as TOS
        previous
----

The first line is required to give the user access to the list of assembler
mnemonics. They are not in the default wordlist path because of their sheer
number: 

----
        adc.# adc.x adc.y adc.z adc.zi adc.ziy adc.zx adc.zxi and. and.# and.x
        and.y and.z and.zi and.ziy and.zx and.zxi asl asl.a asl.x asl.z asl.zx
        bcc bcs beq bit bit.# bit.x bit.z bit.zx bmi bne bpl bra brk bvc bvs clc
        cld cli clv cmp cmp.# cmp.x cmp.y cmp.z cmp.zi cmp.ziy cmp.zx cmp.zxi
        cpx cpx.# cpx.z cpy cpy.# cpy.z dec dec.a dec.x dec.z dec.zx dex dey eor
        eor.# eor.x eor.y eor.z eor.zi eor.ziy eor.zx eor.zxi inc inc.a inc.x
        inc.z inc.zx inx iny jmp jmp.i jmp.xi jsr lda lda.# lda.x lda.y lda.z
        lda.zi lda.ziy lda.zx lda.zxi ldx ldx.# ldx.y ldx.z ldx.zy ldy ldy.#
        ldy.x ldy.z ldy.zx lsr lsr.a lsr.x lsr.z lsr.zx nop ora ora.# ora.x
        ora.y ora.z ora.zi ora.ziy ora.zx ora.zxi pha php phx phy pla plp plx
        ply rol rol.a rol.x rol.z rol.zx ror ror.a ror.x ror.z ror.zx rti rts
        sbc sbc.# sbc.x sbc.y sbc.z sbc.zi sbc.ziy sbc.zx sbc.zxi sec sed sei
        sta sta.x sta.y sta.z sta.zi sta.ziy sta.zx sta.zxi stx stx.z stx.zy sty
        sty.z sty.zx stz stz.x stz.z stz.zx tax tay trb trb.z tsb tsb.z tsx txa
        txs tya
----

The last line in our code, `previous`, removes the assembler wordlist again.

In the example above, it is important to use `rts` and not `brk` as the last
instruction to return to the command line.

WARNING: Seriously. Never use `brk` inside Tali Forth assembler code!

Note you can freely mix Forth high-level words and assembler instructions. For
example, this will work:

----
        hex
        10 lda.#        \ LDA #$10
        decimal
        10 ldx.#        \ LDA #10
----

Running the disassembler gives us (actual addresses may vary):

----
        12BF    10 lda.#
        12C1     A ldx.#
----

This also allows the use various different formatting tricks like putting more
than one assembler instruction in a line or including in-line comments:

----
        dec.a dec.a     \ DEC twice
        nop ( just chilling ) nop ( still don't want to work )
        nop ( not going to happen ) nop ( just go away already! )
----

==== Adding assembler code to new words

The assembler words are immediate, that is, they are executed even during
compilation. Simply adding them to a word doesn't work. For example, if we want
a word that pushes 1 on the Forth data stack, we might be tempted to do this
(assuming `assembler-wordlist >order` first):

----
        : one-to-tos  compiled
        1 lda.#                 \ fails with "Stack underflow"
----

The problem is that the number `1` is compiled, and then the immediate word
`lda.#` is executed, but it can't find its operand on the stack. To avoid this
problem, we can use the `[` and `]` words:

----
        : one-to-tos  compiled
        [ 1 lda.# ]  compiled
        [ push-a ]  compiled
        u. ;  ok
----

NOTE: We do not need to add an explicit `rts` instruction when compiling new
words with assembler because the `;` does it automatically. This is because Tali
Forth uses Subroutine Threaded Code (STC).

Running `one-to-tos` prints the number `1`. We can use a slightly simpler variant:

----
        : one-to-tos  compiled
        [ 1 lda.#  ok   
        push-a ]  compiled
        u. ;  ok
----

This time, we've only used one left square bracket to start the assembler code
and one right bracket to end it. Because of this, we get `ok` instead of
`compiled` because we are technically not in compile-mode anymore. `1 lda.#` can
write the machine code right away.

Looking at our new word with `see` gives us (addresses may vary):

----
        nt: A2A  xt: A3C 
        flags (CO AN IM NN UF HC): 0 0 0 1 0 1 
        size (decimal): 19 

        0A3C  A9 01 CA CA 95 00 74 01  20 3D D6 20 89 D6 A9 20  ......t.  =. ... 
        0A4C  20 30 8E   0.

        A3C      1 lda.#   <1>
        A3E        dex     <2>
        A3F        dex
        A40      0 sta.zx
        A42      1 stz.zx
        A44   D63D jsr     <3>
        A47   D689 jsr
        A4A     20 lda.#
        A4C   8E30 jsr
----
<1> The `1 lda.#` as a single line; 
<2> Four lines of code for `push-a`; 
<3> Four lines from `u.`

Some Forths add the words `code` and `end-code` to mark the beginning and end of
an assembler blocks. In our case, these would just be simple synonyms for `[`
and `]`, so we don't bother.


==== Accessing Forth words from assembler

To execute Forth words when then assembler code is run, we need to store a
subroutine jump to the word's execution token (xt). This we can get with `'`
("tick"). For instance, to print the byte in the accumulator:

----
        here
        10 lda.#
        push-a          <1>
        ' u. jsr        <2>
        rts
        execute
----
<1> Push the value from A to TOS
<2> Code a subroutine jump to `u.`

This will print `10`.

==== Labels, jumps, and branches

The support for labels is currently very limited. An anonymous label can be
marked with `+-->+` (the "arrow") as a target for a backwards jump with `<j`
(the "back jump". A primitive example (that produces an endless loop):

----
        : .nums
        [ 0 lda.#
        -->                     ; anonymous label
        inc.a push-a pha ]      ; PHA required because u. will overwrite A
        u.
        [ pla <j jmp ]          ; endless loop
        ; 
----

Executing the word `.nums` will print numbers starting with 1 till 255 and then
wrap.

The directive `<j` is actually a dummy, or to put a bit more politely, syntactic
sugar: The `jmp` instruction itself takes the value from the stack. `+-->+`
itself is nothing more than an immediate version of `here` and in fact shares
the same assembler code.

Disassembling `.nums` shows how this code works (addresses may vary):

----
        99D      0 lda.#
        99F        inc.a   <1>
        9A0        dex
        9A1        dex
        9A2      0 sta.zx
        9A4      1 stz.zx
        9A6        pha
        9A7   D676 jsr
        9AA   D6C2 jsr
        9AD     20 lda.#
        9AF   8E18 jsr
        9B2        pla
        9B3    99F jmp     <2>
----
<1> Address specified by label `+->+` is `$099F`
<2> Address was picked up by `jmp` instruction

Branches work similar. Instead of `<j` as a "back jump", we use `<b` as a "back
branch". For example, this word takes a number of "a" to print (in slightly
different notation):

----
        : .na ( n -- )
        [ 
              0 lda.zx  <1>
                tay 
        --> 
             97 lda.#  
                push-a 
                phy 
        ]
        emit
        [ 
                ply 
                dey  
             <b bne
                inx  <2>
                inx 
        ]
        ; 
----
<1> `LDA 0,X` in traditional notation
<2> Assembler version of `drop`

Looking at the assembler code with `see`, we can see that the branch instruction
takes $F2 as an operand. 

Currently, there is no mechanism that checks to see if the operand is in the
correct range for a branch. It is assumed that the assembler will be used only
for small code snippets where this will not be a problem.


==== Pseudo-instructions and macros

**push-a** takes the byte in the Accumulator A and pushes it to the top of the
Forth Data Stack. This is a convenience macro for

----
        dex
        dex
        sta.zx 0        ; STA 0,X
        stz.zx 1        ; STZ 1,X
----

==== Under the hood

The assembler instructions are in fact just normal, very simple Forth words that 
send the opcode and the length of the instruction in bytes to common routines
for processing.

The assembler instructions will trigger an underflow error if there is no
operand on the stack when required.

----
        lda.#   \ requires operand first on the stack -> triggers error
----

==== Gotchas and known issues

Working with assembler requires an intimate knowledge of Tali Forth's internals.
Some of the things that range from just very dangerous to downright suicidal
are:

*Using the X register.* Tali Forth uses X to hold the Data Stack pointer.
Manipulating it risks crashing the whole system beyond any hope of recovery. If
for some reason you feel you must use X, be careful to save and restore the
original value, such as:

----
        phx
        ( do something with X )
        plx
----

*There are currently no forward branches.* The words `b>` and `j>` will be used
once they are added. Forward branches are more complex because they require
backtracking to fill in the address that is not known when the jump or branch
instruction is coded.

*The assembler instruction `and`* receives a dot for absolute addressing to avoid
conflict with the Forth word of the same name: `and. 1000` is the correct form.

*`brk` is a two-byte instruction* because the assembler enforces the signature
byte. You shouldn't use `brk` anyway.


==== Other ways to insert assembler code

Sometimes the assembler can be overkill, or we are given a dump of hex values
from a different assembler to store. Probably the very simplest way is to add
the opcodes and operands directly with the `c,` instruction to store the machine
code byte by byte. Our very first example of pushing the number 1 to the Data
Stack in assembler  becomes:

----
        hex  here a9 c, 01 c, ca c, ca c, 95 c, 00 c, 74 c, 01 c, 60 c,
----

This leaves the address of this routine on the stack through the `here`. We run
this fragment with `execute` and find the number 1 on the stack.

This, however, is error-prone to type. Tali Forth provides a special word
called `hexstore ( addr u addr1 -- u )` for those occasions. It stores the
string provided by `( addr u )` at the location `addr1` and returns the number of
bytes stored.

----
       hex  
       s" a9 01 ca ca 95 00 74 01 60" 6000 hexstore
       drop     <1>
       6000 execute
----
<1> Get rid of return value bytes stored

This word can be tricky to use with `here` because the string storage command
`s"` uses memory. The current address must be chosen _before_ the string is
stored:

----
        hex
        here dup  s" a9 01 ca ca 95 00 74 01 60" rot hexstore 
        drop execute 
----

Instead of `drop execute` in the last line, a `dump` will show that the correct
bytes were stored (address may vary):

----
        0990  A9 01 CA CA 95 00 74 01  60  ......t. `
----

Disassembly gives us the fragment we were expecting:

----
        9AD      1 lda.#
        9AF        dex
        9B0        dex
        9B1      0 sta.zx
        9B3      1 stz.zx
        9B5        rts
----

Note here again the `rts` as last instruction.

We can also use the line-editor `ed` to add hex values for `hexstore`, which
makes it easier to correct typing errors. Adding our code:

----
        ed
        a
        a9 01 ca ca 95 00 74 01 60
        .
        5000w  <1>
        27     <2>
        q
----
<1> Save string at address 5000
<2> Shows us length of number string saved

Unless we ran `hex` before adding the word, the string is no stored at the
decimal addresss 5000. However, we've added the words as hexadecimal code. To
call `hexstore`, we must switch at the right time:

----
        5000 27 6000 hex hexstore  ok
        drop 
        decimal 
        6000 execute 
----

You can get around this by either using all-hex numbers or enter the number
string in decimal.

