Tali supports the optional BLOCK word set. The 2012 Forth standard
defines a block as 1024 bytes, and the buffers for them are the same
size (as opposed to some older forths that had smaller buffers.) Tali
currently comes with one buffer.

Before these words can be used, the user needs to write two routines: one for
reading blocks into RAM and one for writing blocks out from RAM. Both of these
should have the signature `( addr blk# -- )`. Once these have been written, they
can be incorporated into the BLOCK word set by changing the vectors for words
`block-read` and `block-write`. That might look like:

----
' myblockreader BLOCK-READ-VECTOR !
' myblockwriter BLOCK-WRITE-VECTOR !
----

These vectors determine what runs when the words `block-read` and
`block-write` are used.  Both of these words start with an error
message asking you to update the vectors.  Once these two vectors have
been updated, you can use the block words.

If you would like to play with some blocks, but don't have any
hardware or are running Tali in a simulator, fear not!  Tali has a
built-in RAM drive that can be accessed by running:

----
4 block-ramdrive-init
----

This reserves a chunk of ram with four blocks in it (numbered 0-3) which is
enough to play around with. It also sets up the routines for reading and writing
blocks in this ramdrive for you. If you want more blocks, you can change the
number. Because they start at zero, the last valid block will always be one less
than the number you provide.

Be careful about creating too many blocks as they are 1K each.  It's also worth
noting that running `block-ramdrive-init` again will create another ramdrive and
the existing one will be inaccessible while still taking up space in
RAM.

See the tutorials on working with blocks for more information on how to use them.