Tali Forth is currently shipped with a very primitive disassembler, which is
started with `disasm ( addr u -- )`. 

==== Format

The output format is in Simpler Assembler Notation (SAN) which adds the mode of
an instruction to the main mnemonic, simplifying parsing of code. For instance,

----
lda #1
sta $1000,x
sta $80
lda ($80)
----

becomes

----
lda.# 1
sta.x $1000
sta.z $80
lda.di $80
----

A full discussion of SAN is beyond the scope of this document, see
https://docs.google.com/document/d/16Sv3Y-3rHPXyxT1J3zLBVq4reSPYtY2G6OSojNTm4SQ/edit#heading=h.ik059qk0tz7r[this
link] for an overview of the format (currently still under a different name).


==== Replacing the Disassembler

Tali was designed to make it easy for the user to swap in a different
disassembler. The code is in a separate file, `disassembler.asm`. To replace
this by your version, move the file to a different name, make sure that it
accepts `( addr u )` on the Forth Data Stack as parameters, and start your code
after the label `disassembler:`.

