TIP: This manual includes <<ed-tutorial,a tutorial>> for `ed`

[quote, B. W. Kernighan, A Tutorial Introduction to the UNIX Text Editor]
Ed makes no response to most commands – there is no prompting or typing of
messages like "ready". (This silence is preferred by experienced users, but
sometimes a hangup for beginners.) <<BWK>>

Tali Forth 2 currently ships with a clone of the `ed` line-based editor of
Unix fame. It is envoked with `ed` and does not change the data stack. The
formal name is `ed6502`. 

WARNING: `ed` is included in a very primitive form only and should be considered
ALPHA. 

==== Supported Commands

`ed` currently supports only a small number of the commands of the Unix version:

[horizontal]
a:: Add new lines below given line
d:: Delete line
f:: Show current target address for writes (`w`)
i:: Add new lines above given line
q:: Quit if no unsaved work
Q:: Unconditional quit, unsaved work is lost
w:: Write text to given memory location (eg `7000w`)
=:: Print value of given parameter (eg `$=` gives number of last line)

For the parameters, these are currently available:

[horizontal]
 .:: Current line number
,:: When alone: All lines, the same as `1,$` or `%`
;:: Range from current line to end, same as `.,$`
$:: Last line
%:: All lines, the same as `1,$` or `,` alone

An empty line (pressing the ENTER key) will advance by one line and print it. A
simple number will print that line without the line number and make that line
the new current line.

==== Future planned commands

There is no time frame for these additions. 

[horizontal]
+:: Advance by one line, print it and make it the new current line
-:: Go back by one line, print it and make it the new current line
c:: Change a line, possibly adding new lines
e:: Edit lines given as `addr,u` in text buffer
j:: Join two lines to a new line
m:: Move block of text to new line
r:: Append text from a block to end of text buffer
s:: Substitute one string on line with another
!:: Execute a shell command (Forth command in our case)
#:: Comment, ignore rest of the line

==== Differences to Unix ed

(Apart from missing about 90 percent of the features, that is)

- The `w` (write) command takes its parameter before and not after the word.
  Where Unix ed uses the format `w <FILENAME>`, ed6502 takes the address
  to write the text to as `7000w`.

WARNING: At this point, it isn't totally clear what happens if the number base
is set to hexadecimal via `hex`. Use at your own risk.


==== Using `ed` for programming

`Ed` can be used to write programs and then execute them with `evaluate`. For
instance, a session to add a small string could look something like this:

----
ed
a
.( Shepard, is that ... You're alive?)
.
7000w <1>
22 <2>
q
----
<1> Address we save the command to
<2> Number of characters saved including final line feed

It is a common mistake to forget the `.` (dot) to end the input, and try to
go immediately to saving the text. Then, we can run the program:

----
7000 22 evaluate
----

Ǹote that `evaluate` will handle line feeds, carriage returns and other white
space apart from simple spaces without problems.

==== Known Issues

===== Memory use

`Ed` currently uses memory without releasing it when done. For small, quick
edits, this probably is not a problem. However, if you known you are going to be
using more memory, you probably will want to set a marker first.

----
marker pre-edit <1>
ed <2>
pre-edit <3>
----
<1> Set marker at current value of `here`
<2> Edit normally
<3> Call marker, releasing memory

This issue might be taken care of in a future release.

===== Address of Saved Text

Currently, `ed` returns the data stack just the way it found it. This means
that you have to remember where you saved the text to with `w` and how long it
was. A different option would be to return `( -- addr u )`, that is, the address
and length of the text we saved. If nothing is saved, the program would return a
zero length as TOS.

==== Developer Information

`Ed` will be massively rewritten under the hood once the code has been
stabilized, has all features, and a testing suite. Currently, it's somewhat of a
mess and contains some testing routines that will be removed in the final
version.

The "buffer" of `ed` is a simple linked list of nodes, consisting of a pointer
to the next entry, a pointer to the string address, and the length of that
string. Each entry is two byte, making six bytes in total for each node. A value
of 0000 in the pointer to the next address signals the end of the list. The
buffer starts at the point of the `cp` (accessed with the Forth word `here`) and
is only saved to the given location when the `w` command is given.
