[quote, Charles Moore, Masterminds of Programming]
One doesn't write programs in Forth. Forth is the program.

=== Booting

Out of the box, Tali Forth boots a minimal kernel(((kernel))) to connect to the
`py65mon` (((py65mon))) simulator. By default, this stage ends with a line such
as

----
Tali Forth 2 default kernel for py65mon (18. Feb 2018)
----

When you port Tali Forth to your own hardware, you'll have to include your own
kernel (and probably should print out a different line).

Tali Forth itself boots next, and after setting up various internal
things, compiles the high level words. This causes a slight delay, depending on
the number and length of these words. As the last step, Forth should spit out a
boot string like

----
Tali Forth 2 for the 65c02
Version ALPHA 02. July 2018 
Copyright 2014-2018 Scot W. Stevenson
Tali Forth 2 comes with absolutely NO WARRANTY
Type 'bye' to exit
----

Because these are the last high-level commands Tali Forth executes, this
functions as a primitive self-test. If you have modified the high level Forth
words in either `forth_words.fs` or `user_words.fs`, the boot process might
fail with a variant of the error message "unknown word". The built-in, native
words should always work. For this `dump` (((dump))) is a built-in word -- it is very
useful for testing.

=== Command-Line History
                                               
Tali's command line includes a simple, eight-element history function. To
access the previous entries, press `CONTROL-p`, to go forward to the next
entry, press `CONTROL-n`.
 
=== Words

Tali Forth comes with the following Forth words out of the 
box:

----
see block_init_ramdrive evaluate thru load flush empty-buffers buffer update 
block save-buffers block_words_deferred blockwrite blockread scr blk buffstatus 
buffblocknum blkbuffer 2literal 2constant d.r d. ud.r ud. .r u.r action-of is defer@ 
defer! endcase endof of case while until repeat else then if .( ( drop dup swap ! @ 
over >r r> r@ nip rot -rot tuck , c@ c! +! execute emit type . u. ? false true 
space 0 1 2 2dup ?dup + - abs dabs and or xor rshift lshift pick char [char] char+ 
chars cells cell+ here 1- 1+ 2* 2/ = <> < u< u> > 0= 0<> 0> 0< min max 2drop 2swap 
2over 2! 2@ 2variable 2r@ 2r> 2>r invert negate dnegate c, bounds spaces bl 
-trailing /string refill accept unused depth key allot create does> variable constant 
value to s>d d>s d- d+ erase blank fill find-name ' ['] name>int int>name 
name>string >body defer latestxt latestnt parse-name parse source source-id : ; :noname 
compile, [ ] 0branch branch literal sliteral ." s" postpone immediate compile-only 
never-native always-native nc-limit uf-strip abort abort" do ?do i j loop +loop exit 
unloop leave recurse quit begin again state evaluate base digit? number >number hex 
decimal count m* um* * um/mod sm/rem fm/mod / /mod mod */mod */ \ move cmove> cmove 
pad within >in <# # #s #> hold sign output input cr page at-xy marker words 
wordsize aligned align bell dump .s disasm compare search environment? find word cold 
bye
----

NOTE: This list might be outdated. To get the current list, run `words` from
inside Tali Forth.

Though the list might look unsorted, it actually reflects the priority in the
dictionary(((dictionary))), that is, which words are found first. For instance,
the native words (((native words))) -- those coded in assembler -- always start
with `drop` and end with `bye`. This is the last word that Tali will find in
the dictionary. footnote:[If you're going to quit anyway, speed can't be that
important] The words before `drop` are those that are defined in high-level
Forth. For more information on individual the words, use the `see` command.

Note that the built-in words are lower case.  While Tali is not case sensitive
-- `KASUMI` is the same word as `Kasumi` (((Kasumi))) -- newly defined words will be
lowercased as they are created and entered into the dictionary.  There is a
slight speed advantage during lookup to using lowercase words (because Tali
doesn't have to lowercase the entered text), so all of the tests for Tali are
in lowercase.

                                               
==== The ANS Standard
                                   
Tali Forth is orientated on ANS Forth, the standard defined by the American
National Standards Institute (ANSI). Tali also adopted some words from Gforth
such as `bounds`. In practical terms, Tali aims to be a subset of Gforth: If a
program runs on Tali, it should run on Gforth the same way or have a very good
reason not to.

==== Tali-Specific Words
                                               
In addition, there are words that are specific to Tali Forth.  

[horizontal]
0branch:: `( f -- )` Branch if zero. Used internally for branching commands such as `if`.
In modern Forths, this is usually replaced by `cs-pick` and `cs-roll`; Tali Forth
might switch to these words in the future.
0:: `( -- 0 )` Push the number 0 on the Data Stack.
1:: `( -- 0 )` Push the number 1 on the Data Stack.
2:: `( -- 0 )` Push the number 2 on the Data Stack.
always-native:: Mark last word in dictionary so that it is always natively compiled.
bell:: Ring the terminal bell (ASCII 07).
block-read:: `( addr blk# -- )` This is a deferred word the user can change to point 
to their own routine for reading 1K blocks into memory from storage.
block-write:: `( addr blk# -- )` This is a deferred word the user can change to point 
to their own routine for writing 1K blocks from memory to storage.
block-ramdrive-init:: `( u -- )` Create a ram drive with the given number of blocks 
(numbered 0 to (u-1)) to
allow use of the block words with no additional hardware.  Because the blocks are
only held in ram, they will be lost when the hardware is powered down or the simulator
is stopped.
branch:: Always take branch. See `0branch`.
compile-only:: Mark last word in dictionary as compile-only.
digit?:: `( char -- u f | char f )` If character is a digit, convert and set flag to
`true`, otherwise return the offending character and a `false` flag.
input:: Return the address where the vector for the input routine is
stored (not the vector itself). Used for input redirection for
`emit` and others.
int>name:: `( xt -- nt )` Given the execution execution token (xt), return the
name token (nt).
latestnt:: `( -- nt )` Return the last used name token. The Gforth version of this
 word is called `latest`.
nc-limit:: `( -- addr )` Return the address where the threshold value for native
compiling native compiling is kept. To check the value of this parameter, use `nc-limit ?`. 
The default value is 20.
never-native:: Mark most recent word so it is never natively compiled.
number:: `( addr u -- u | d )` Convert a string to a number.  Gforth uses
`s>number?` and returns a success flag as well.
output:: `( -- addr )` Return the address where the vector for the output routine is
stored (not the vector itself). Used for output redirection for `emit` and
others.
uf-strip:: `( -- addr)` Return the address where the flag is kept that decides
if the underflow checks are removed during native compiling. To check the value
of this flag, use `uf-strip ?`.
wordsize:: `( nt -- u )` Given the name token (nt) of a Forth word, return its
size in bytes. Used to help tune native compiling.
=== Native Compiling

As the name says, subroutine threaded code encodes the words as a series of
subroutine jumps. Because of the overhead caused by these jumps, this can make
the code slow. Therefore, Tali Forth enables native compiling, where the
machine code from the word itself is included instead of a subroutine jump. This
is also called "inlining".

The parameter `nc-limit` sets the limit of how small words have to be to be
natively compiled. To get the current value (usually 20), check the value of
the system variable:

----
nc-limit ?
----

To set a new limit, save the maximal allowed number of bytes in the machine
code like any other Forth variable:

----
40 nc-limit !
----

To complete turn off native compiling, set this value to zero.


=== Underflow Detection

When a word tries to access more words on the stack than it is holding, an
"underflow" error occurs. Whereas Tali Forth 1 didn't check
for these errors, this version does.

However, this slows the program down. Because of this, the user can turn off
underflow detection for words that are natively compiled into new words. To do
this, set the system variable `uf-strip` to `true`. Note this does not turn off
underflow detection in the built-in words. Also, words with underflow detection
that are not included in new words through native compiling will also retain
their tests.

=== Restarting

Tali Forth has a non-standard word `cold` that resets the system. This doesn't
erase any data in memory, but just moves the pointers back. When in doubt, you
might be better off quitting and restarting completely.

=== Gotchas

==== Cell Size

Tali has a 16-bit cell size. 

NOTE: Use `1 cells 8 * .` to get the cell size in bits with any Forth.

This can trip up calculations when compared to the _de facto_ standard Gforth
with 64 bits. Take this example:

----
( Gforth )      decimal 1000 100 um* hex swap u. u.  ( returns 186a0 0  ok )
( Tali Forth)   decimal 1000 100 um* hex swap u. u.  ( returns 86a0 1  ok ) 
----

Tali has to use the upper cell of a double-celled number to correctly report
the result, while Gforth doesn't. If the conversion from double to single is
only via a `drop` instruction, this will produce different results.

There is a similar effect with the Gforth word `bounds`: Because of Tali's 16
bit address space, it wraps the upper address if we go beyond $FFFF:

---- 
( Gforth )      hex FFFF 2 bounds  swap u. u.  ( returns 10001 ffff  ok  )
( Tali )        hex FFFF 2 bounds  swap u. u.  ( returns     1 ffff  ok )
----

==== Negative ALLOT

The ANSI standard does not define what happens if there is an attempt to free
more memory with `allot` by passing a negative value than is available. Tali
will let the user free memory up the beginning of RAM assigned to the Dictionary
(marked with `cp0` in the code), even though this can mean that the Dictionary
itself is compromised. This is Forth, you're the boss.

However, any attempt to free more memory than that will set the beginning of RAM
to `cp0`. Also, the Dictionary Pointer `dp` will point to the _last native word_
of the Dictionary, which is usually `drop`. Because of this, the high level
words defined during boot will _not_ be available. There will be an error
message to document this. Realistically, you'll probably want to restart with
`cold` if any of this happens.


