= Manual for Tali Forth 2 for the 65c02
:doctype: book
:author: Scot W. Stevenson
:email: scot.stevenson@gmail.com
:keywords: forth, 6502, assembler, programming
:revnumber: ALPHA
:revdate: 02. July 2018
:showtitle:
:icons: font
:toc: left

Tali Forth 2 is a bare-metal ANSI(ish) Forth for the 65c02 8-bit MPU. It aims
to be, roughly in order of importance, easy to try out (just run the included
binary), simple (subroutine threading model), specific (for the 65c02 only), and
standardized (ANSI Forth). 

[dedication]
== Dedication

For the crew at 6502.org, who made this possible in more ways than one.


// --------------------------------------------------------
= Introduction

== But why?
include::ch_why.adoc[]

== Overview of Tali Forth
// TODO include file ch_overview_


// --------------------------------------------------------
= User Guide

== Installing Tali Forth
include::ch_installing.adoc[]

== Running Tali Forth
include::ch_running.adoc[]

== Major Components

=== Editor

WARNING: Currently, there is no editor included. The plan is to include a simple
line-based editor in the style of `ed`. 

=== Assembler

WARNING: Currently, there is no assembler included. The plan is to include a simple
assembler based on Simpler Assembler Notation (SAN).

=== Disassembler
include::ch_disasm.adoc[]


// --------------------------------------------------------
= Developer Guide

== How Tali Forth works
include::ch_internals.adoc[]

== Developing
// TODO include ch_developing

== Future and Long-Term plans
WARNING: This section is missing. See the GitHub page for further details.


// --------------------------------------------------------
= Appendix

== Reporting Problems

The best way to point out a bug or make any other form of a comment is on Tali
Forth's page on GitHub at https://github.com/scotws/TaliForth2 There, you can
"open an issue", which allows other people who might have the same problem to
help even when the author is not available.

== FAQ
include::ch_faq.adoc[]

== Testing Tali Forth 2
include::ch_tests.adoc[]

== Thanks
include::ch_thanks.adoc[]

[bibliography]
== References and Further Reading
include::ch_bibliography.adoc[]


// --------------------------------------------------------
[colophon]
== Colophon

The Tali Forth 2 Manual was written with the https://www.vim.org/[vim] editor in
https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] format, formatted to
HTML with AsciiDoctor, and version controled with https://git-scm.com/[Git], all
under https://www.ubuntu.com/[Ubuntu] Linux 16.04 LTS.

